In [2]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Input data (XOR problem)
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])
# Expected output (XOR function)
expected_output = np.array([[0],
                            [1],
                            [1],
                            [0]])

# Seed for reproducibility
np.random.seed(0)

# Initialize weights randomly
input_layer_neurons = 2
hidden_layer_neurons = 2
output_neurons = 1

weights_input_hidden = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

# Learning rate
learning_rate = 0.5

# Training process
for epoch in range(10000):
    # Forward propagation
    hidden_layer_input = np.dot(inputs, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    predicted_output = sigmoid(output_layer_input)

    # Backpropagation
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Updating weights
    weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    weights_input_hidden += inputs.T.dot(d_hidden_layer) * learning_rate

    # Output the error and predicted output every 1000 iterations
    if epoch % 1000 == 0:
        print(f"Epoch {epoch} Error: {np.mean(np.abs(error))}")
        print("Predicted Output:\n", predicted_output)

# Final output after training
print("\nFinal Output after training:")
print(predicted_output)


Epoch 0 Error: 0.4982223878379592
Predicted Output:
 [[0.63059599]
 [0.66432327]
 [0.66869443]
 [0.69531126]]
Epoch 1000 Error: 0.41332545852621355
Predicted Output:
 [[0.37749549]
 [0.6082432 ]
 [0.60913298]
 [0.49318252]]
Epoch 2000 Error: 0.2766309605870447
Predicted Output:
 [[0.21191105]
 [0.72895788]
 [0.72895916]
 [0.35252983]]
Epoch 3000 Error: 0.2128484134771529
Predicted Output:
 [[0.14832896]
 [0.78768714]
 [0.78768739]
 [0.27843923]]
Epoch 4000 Error: 0.17642259095058613
Predicted Output:
 [[0.11563793]
 [0.82210377]
 [0.82210387]
 [0.23426008]]
Epoch 5000 Error: 0.15269677584938973
Predicted Output:
 [[0.09573457]
 [0.84487301]
 [0.84487307]
 [0.20479861]]
Epoch 6000 Error: 0.13588279944549034
Predicted Output:
 [[0.08230067]
 [0.8611827 ]
 [0.86118274]
 [0.18359597]]
Epoch 7000 Error: 0.12325886322613074
Predicted Output:
 [[0.07258812]
 [0.87352581]
 [0.87352584]
 [0.16749899]]
Epoch 8000 Error: 0.11337719548490995
Predicted Output:
 [[0.06521443]
 [0.88324806]
 [0.88324